language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t hgcook/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true hgcook/react-test npm test

after_success:
    - docker build -t hgcook/multi-client ./client
    - docker build -t hgcook/multi-nginx ./nginx
    - docker build -t hgcook/multi-server ./server
    - docker build -t hgcook/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push hgcook/multi-client
    - docker push hgcook/multi-nginx
    - docker push hgcook/multi-server
    - docker push hgcook/multi-worker
    